project: make-map
default_env: prod

envs:
  prod:
    provider: local-dev
    prefix: make-map/prod/
    keys:
      # Backend (Strapi, lecture seule)
      - STRAPI_API_URL
      - STRAPI_API_TOKEN
      # Frontend
      - VITE_API_URL
      - VITE_MAPTILER_KEY
      # Scaleway
      - SCW_ACCESS_KEY
      - SCW_SECRET_KEY
      - SCW_PROJECT_ID
      - SCW_INSTANCE_IP
      # Production
      - DOMAIN
      - CORS_ORIGIN
